default_platform(:android)

platform :android do
  desc "Build a debug APK"
  lane :build_debug do
    gradle(task: "assembleDebug")
  end

  desc "Build a release APK"
  lane :build_release do
    gradle(task: "assembleRelease")
  end
end

