name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK using Flutter
      - name: Build APK
        run: flutter build apk --release

      # Setup Ruby and Bundler
      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # Run Fastlane
      - name: Run Fastlane
        run: |
          cd android
          bundle exec fastlane build_release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Upload APK to MinIO
      - name: Upload APK to MinIO
        env:
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_BUCKET: ${{ secrets.MINIO_BUCKET }}
        run: |
          # Install MinIO client
          curl https://dl.min.io/client/mc/release/linux-amd64/mc -o mc
          chmod +x mc
          ./mc alias set myminio $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

          # Upload the APK
          ./mc cp build/app/outputs/flutter-apk/app-release.apk myminio/$MINIO_BUCKET/app-release.apk
